# -*- coding: utf-8 -*-
"""AIML_task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQwNbag5JXis5quMUuDhsaSZX5THuPcb

# 1. Load and Understand Data
"""

import pandas as pd

df = pd.read_csv('/content/archive (1) (1).zip')
df.head()
df.info()
df.describe()

"""## 2. Summary Statistics"""

print(df.describe())
print(df.isnull().sum())
print(df.nunique())

"""# 3. Data Visualizations"""

#HISTOGRAM
import seaborn as sns
import matplotlib.pyplot as plt

df.hist(figsize=(10, 8))
plt.tight_layout()
plt.show()

#BOXPLOTS(for outliers):
sns.boxplot(x='Survived', y='Age', data=df)

#Count plots (categorical):
sns.countplot(x='Pclass', hue='Survived', data=df)

#Correlation matrix:
import seaborn as sns
import matplotlib.pyplot as plt

# Select only numeric columns
numeric_df = df.select_dtypes(include=['number'])

# Compute and plot the correlation matrix
corr_matrix = numeric_df.corr()

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap of Numeric Features")
plt.show()

#Pairplot
sns.pairplot(df[['Survived', 'Age', 'Fare', 'Pclass']])

"""# 4. Handle Missing Values"""

df['Age'].fillna(df['Age'].median(), inplace=True)
df.drop(columns=['Cabin'], inplace=True)  # too many nulls